server:
  port: 8045

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/categories/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

info:
  app:
    name: API Gateway
    version: 1.0
