server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://product-postgres:5432/productdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://eureka-server:8761/eureka/
